# Generated by Django 4.2.2 on 2023-06-27 21:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description_long",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Полное описание"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="description_short",
            field=models.TextField(verbose_name="Короткое описание"),
        ),
    ]
