# Generated by Django 4.2.2 on 2023-06-27 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0002_alter_post_description_long_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numb", models.IntegerField(verbose_name="Порядковый номер:")),
                (
                    "picturies",
                    models.ImageField(
                        blank=True, upload_to="img", verbose_name="Картинка"
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="places.post",
                        verbose_name="Заголовок",
                    ),
                ),
            ],
        ),
    ]
