# Generated by Django 4.2.2 on 2023-06-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0004_alter_pic_options_remove_pic_title_post_pics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="pics",
        ),
        migrations.AddField(
            model_name="pic",
            name="title",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="places.post",
                verbose_name="Заголовок",
            ),
            preserve_default=False,
        ),
    ]
