# Generated by Django 4.2.2 on 2023-06-28 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0005_remove_post_pics_pic_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pic",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pics",
                to="places.post",
                verbose_name="Заголовок",
            ),
        ),
    ]
