# Generated by Django 4.2.2 on 2023-06-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0006_alter_pic_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="point_lat",
            field=models.FloatField(default=37.62, verbose_name="Широта точки"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="point_lon",
            field=models.FloatField(default=55.793676, verbose_name="Долгота точки"),
            preserve_default=False,
        ),
    ]
