# Generated by Django 4.2.2 on 2023-07-07 00:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0009_post_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pic",
            options={
                "ordering": ["numb"],
                "verbose_name": "Картинка",
                "verbose_name_plural": "Картинки",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="description_long",
            field=tinymce.models.HTMLField(verbose_name="Полное описание"),
        ),
    ]
