# Generated by Django 4.2.2 on 2023-07-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0010_alter_pic_options_alter_post_description_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description_long",
            field=models.TextField(verbose_name="Полное описание"),
        ),
    ]
