# Generated by Django 4.2.2 on 2023-07-07 11:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0011_alter_post_description_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description_long",
            field=tinymce.models.HTMLField(verbose_name="Полное описание"),
        ),
    ]
