# Generated by Django 4.2.2 on 2023-07-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0012_alter_post_description_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Название в виде url",
            ),
        ),
    ]
