# Generated by Django 4.2.2 on 2023-07-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0013_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pic",
            name="numb",
            field=models.IntegerField(blank=True, verbose_name="Порядковый номер:"),
        ),
    ]
