# Generated by Django 4.2.2 on 2023-07-10 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0015_alter_pic_numb"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="description_long",
            new_name="long_description",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="description_short",
            new_name="short_description",
        ),
    ]
